// List all interactive video files (order defines grid filling, max 24 shown)
window.INTERACTIVE_FILES = [
    "interactive-iron.mp4",
    "interactive-trick.mp4",
    "interactive-paul.mp4",
    "interactive-casino.mp4",
    "【形态变化3】熊（最好）.mp4",
    "interactive-birthday.mp4",
    "case7.mp4",
    "interactive-model.mp4",
    "【大幅画面变化1】动作片（最好）.mp4",
    "【大幅画面变化2】科幻片（最好）.mp4",
    "【形态变化2】秋天（最好）.mp4",
    "【风格变化1】草原 （最好）.mp4",
    "【风格变化3】竹林（最好）.mp4",
    "case1_web.mp4",
    "case5.mp4",
    "case6.mp4",
    "interactive-couple.mp4",
    "interactive-crown.mp4",
    "interactive-drown.mp4",
    "interactive-teddy.mp4",
    "interactive-TVshow.mp4",
    "object_case2.mp4",
    "object_case5.mp4",
    "shot_case1.mp4",
];

// Map each filename to its prompt overlay content (fill later)
window.INTERACTIVE_PROMPTS = {
    "interactive-iron.mp4": "",
    "interactive-trick.mp4": "",
    "interactive-paul.mp4": "",
    "interactive-casino.mp4": "",
    "【形态变化3】熊（最好）.mp4": "",
    "interactive-birthday.mp4": "",
    "case7.mp4": "",
    "interactive-model.mp4": "",
    "【大幅画面变化1】动作片（最好）.mp4": "",
    "【大幅画面变化2】科幻片（最好）.mp4": "",
    "【形态变化2】秋天（最好）.mp4": "",
    "【风格变化1】草原 （最好）.mp4": "",
    "【风格变化3】竹林（最好）.mp4": "",
    "case1_web.mp4": "",
    "case5.mp4": "",
    "case6.mp4": "",
    "interactive-couple.mp4": "",
    "interactive-crown.mp4": "",
    "interactive-drown.mp4": "",
    "interactive-teddy.mp4": "",
    "interactive-TVshow.mp4": "",
    "object_case2.mp4": "",
    "object_case5.mp4": "",
    "shot_case1.mp4": "",
};


